// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: pkg/proto/model/encoding/encoding.proto

package encoding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeterministicEncryptingBinaryEncoder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptionKey []byte                 `protobuf:"bytes,1,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeterministicEncryptingBinaryEncoder) Reset() {
	*x = DeterministicEncryptingBinaryEncoder{}
	mi := &file_pkg_proto_model_encoding_encoding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeterministicEncryptingBinaryEncoder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeterministicEncryptingBinaryEncoder) ProtoMessage() {}

func (x *DeterministicEncryptingBinaryEncoder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_encoding_encoding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeterministicEncryptingBinaryEncoder.ProtoReflect.Descriptor instead.
func (*DeterministicEncryptingBinaryEncoder) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_encoding_encoding_proto_rawDescGZIP(), []int{0}
}

func (x *DeterministicEncryptingBinaryEncoder) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

type BinaryEncoder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Encoder:
	//
	//	*BinaryEncoder_LzwCompressing
	//	*BinaryEncoder_DeterministicEncrypting
	Encoder       isBinaryEncoder_Encoder `protobuf_oneof:"encoder"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryEncoder) Reset() {
	*x = BinaryEncoder{}
	mi := &file_pkg_proto_model_encoding_encoding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryEncoder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryEncoder) ProtoMessage() {}

func (x *BinaryEncoder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_encoding_encoding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryEncoder.ProtoReflect.Descriptor instead.
func (*BinaryEncoder) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_encoding_encoding_proto_rawDescGZIP(), []int{1}
}

func (x *BinaryEncoder) GetEncoder() isBinaryEncoder_Encoder {
	if x != nil {
		return x.Encoder
	}
	return nil
}

func (x *BinaryEncoder) GetLzwCompressing() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Encoder.(*BinaryEncoder_LzwCompressing); ok {
			return x.LzwCompressing
		}
	}
	return nil
}

func (x *BinaryEncoder) GetDeterministicEncrypting() *DeterministicEncryptingBinaryEncoder {
	if x != nil {
		if x, ok := x.Encoder.(*BinaryEncoder_DeterministicEncrypting); ok {
			return x.DeterministicEncrypting
		}
	}
	return nil
}

type isBinaryEncoder_Encoder interface {
	isBinaryEncoder_Encoder()
}

type BinaryEncoder_LzwCompressing struct {
	LzwCompressing *emptypb.Empty `protobuf:"bytes,1,opt,name=lzw_compressing,json=lzwCompressing,proto3,oneof"`
}

type BinaryEncoder_DeterministicEncrypting struct {
	DeterministicEncrypting *DeterministicEncryptingBinaryEncoder `protobuf:"bytes,2,opt,name=deterministic_encrypting,json=deterministicEncrypting,proto3,oneof"`
}

func (*BinaryEncoder_LzwCompressing) isBinaryEncoder_Encoder() {}

func (*BinaryEncoder_DeterministicEncrypting) isBinaryEncoder_Encoder() {}

var File_pkg_proto_model_encoding_encoding_proto protoreflect.FileDescriptor

var file_pkg_proto_model_encoding_encoding_proto_rawDesc = string([]byte{
	0x0a, 0x27, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64,
	0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x62, 0x6f, 0x6e, 0x61, 0x6e,
	0x7a, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d,
	0x0a, 0x24, 0x44, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x69, 0x63, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x22, 0xd8, 0x01,
	0x0a, 0x0d, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x12,
	0x41, 0x0a, 0x0f, 0x6c, 0x7a, 0x77, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x48, 0x00, 0x52, 0x0e, 0x6c, 0x7a, 0x77, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x12, 0x79, 0x0a, 0x18, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x5f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x62, 0x6f, 0x6e, 0x61, 0x6e, 0x7a, 0x61, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65,
	0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x69, 0x63, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x45, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x17, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x09, 0x0a,
	0x07, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e,
	0x2f, 0x62, 0x6f, 0x6e, 0x61, 0x6e, 0x7a, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_proto_model_encoding_encoding_proto_rawDescOnce sync.Once
	file_pkg_proto_model_encoding_encoding_proto_rawDescData []byte
)

func file_pkg_proto_model_encoding_encoding_proto_rawDescGZIP() []byte {
	file_pkg_proto_model_encoding_encoding_proto_rawDescOnce.Do(func() {
		file_pkg_proto_model_encoding_encoding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_model_encoding_encoding_proto_rawDesc), len(file_pkg_proto_model_encoding_encoding_proto_rawDesc)))
	})
	return file_pkg_proto_model_encoding_encoding_proto_rawDescData
}

var file_pkg_proto_model_encoding_encoding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_model_encoding_encoding_proto_goTypes = []any{
	(*DeterministicEncryptingBinaryEncoder)(nil), // 0: bonanza.model.encoding.DeterministicEncryptingBinaryEncoder
	(*BinaryEncoder)(nil),                        // 1: bonanza.model.encoding.BinaryEncoder
	(*emptypb.Empty)(nil),                        // 2: google.protobuf.Empty
}
var file_pkg_proto_model_encoding_encoding_proto_depIdxs = []int32{
	2, // 0: bonanza.model.encoding.BinaryEncoder.lzw_compressing:type_name -> google.protobuf.Empty
	0, // 1: bonanza.model.encoding.BinaryEncoder.deterministic_encrypting:type_name -> bonanza.model.encoding.DeterministicEncryptingBinaryEncoder
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_model_encoding_encoding_proto_init() }
func file_pkg_proto_model_encoding_encoding_proto_init() {
	if File_pkg_proto_model_encoding_encoding_proto != nil {
		return
	}
	file_pkg_proto_model_encoding_encoding_proto_msgTypes[1].OneofWrappers = []any{
		(*BinaryEncoder_LzwCompressing)(nil),
		(*BinaryEncoder_DeterministicEncrypting)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_model_encoding_encoding_proto_rawDesc), len(file_pkg_proto_model_encoding_encoding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_model_encoding_encoding_proto_goTypes,
		DependencyIndexes: file_pkg_proto_model_encoding_encoding_proto_depIdxs,
		MessageInfos:      file_pkg_proto_model_encoding_encoding_proto_msgTypes,
	}.Build()
	File_pkg_proto_model_encoding_encoding_proto = out.File
	file_pkg_proto_model_encoding_encoding_proto_goTypes = nil
	file_pkg_proto_model_encoding_encoding_proto_depIdxs = nil
}
