package varint

import (
	"math/bits"

	"golang.org/x/exp/constraints"
)

// SizeBytes returns the size of the variable length encoded integer
// generated by AppendBackward() or AppendForward().
func SizeBytes[T constraints.Integer](value T) int {
	var v uint64
	if value < 0 {
		v = ^uint64(int64(value))
	} else {
		v = uint64(value)
	}
	return bits.Len64(v)/7 + 1
}
